export { default as DashboardPage } from "./Dashboard";
export { default as DashboardSongPage } from "./song";
export { default as DashboardAddSongPage } from "./song/add-song";
export { default as DashboardEditSongPage } from "./song/edit-song";
export { default as DashboardPlaylistPage } from "./playlist";
export { default as DashboardPlaylistDetailPage } from "./playlist-detail";
export { default as DashboardSingerPage } from "./singer";
export { default as DashboardGenrePage } from "./genre";
export { default as DashboardSongLyricPage } from "./edit-song-lyric";
