export { default as Home } from "./home";
export { default as Playlist } from "./playlist";
export { default as MyMusic } from "./my-music";
export { default as EditSongLyric } from "./edit-song-lyric";
export { default as Search } from "./search";
export { default as NotFoundPage } from "./others/NotFound";
export { default as Unauthorized } from "./others/Unauthorized";
export { default as Login } from "./Login";
export { default as SingerPage } from "./singer";
